# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "TUI for bookmarking and resuming Claude Code and Codex sessions"
  homepage "https://github.com/jaredgizersky/stash"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaredgizersky/stash/releases/download/v0.1.1/stash_0.1.1_darwin_amd64.tar.gz"
      sha256 "5ea1b671d097a345d11f57a8d8e430ac39dc416f76d84466c183e6ddc83219a4"

      define_method(:install) do
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaredgizersky/stash/releases/download/v0.1.1/stash_0.1.1_darwin_arm64.tar.gz"
      sha256 "42d348005543c2793248d5b2e5784110255c036424a14b38bb3b10743b03dec1"

      define_method(:install) do
        bin.install "stash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaredgizersky/stash/releases/download/v0.1.1/stash_0.1.1_linux_amd64.tar.gz"
      sha256 "7b562578c4ccaf838151d79caa36632af1f485498171807a6482306018ee0eb6"
      define_method(:install) do
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaredgizersky/stash/releases/download/v0.1.1/stash_0.1.1_linux_arm64.tar.gz"
      sha256 "4f106bcb48d8db68b5226393f32b49bff2bf3e397db4badad8269d0cefeba4b6"
      define_method(:install) do
        bin.install "stash"
      end
    end
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/stash --help")
  end
end
